name: BayMcPatrol
version: '${version}'
main: com.baymc.patrol.BayMcPatrolPlugin
api-version: '1.21'
folia-supported: true
authors: [Konsheng]
website: "https://github.com/konsheng/BayMcPatrol"
description: Paper / Folia 现代玩家巡查插件

commands:
  baymcpatrol:
    description: 跨服随机巡查传送
    usage: /baymcpatrol [help|next|back|reload|status]
    aliases:
      - patrol

permissions:
  baymcpatrol.use:
    description: 允许使用 /patrol 和 /patrol next
    default: op

  baymcpatrol.back:
    description: 允许使用 /patrol back
    default: op

  baymcpatrol.status:
    description: 允许使用 /patrol status
    default: op

  baymcpatrol.reload:
    description: 允许使用 /patrol reload
    default: op

  baymcpatrol.bypass:
    description: 拥有该权限的玩家不会被随机巡查到
    default: false
